application: sarah-gae
version: v0-0-1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico
- url: /static
  static_dir: static
  application_readable: True
- url: .*  # This regex directs all routes to tito.app
  script: hello_world.app

libraries:
#- name: django
#  version: 1.5
- name: MySQLdb
  version: "latest"
- name: ssl
  version: "latest"
- name: PIL
  version: "latest"
